export const ActionTypes = {
    SET_QUSTIONS : "SET_QUSTIONS",
    SELECTED_QUESTION : "SELECTED_QUESTION",
    START_INTERVIEW : "START_INTERVIEW",
    CHANGE_INTERVIEW_STATUS : "CHANGE_INTERVIEW_STATUS",
    SAVE_QUESTION_CHANGES : "SAVE_QUESTION_CHANGES",
    DELETE_QUESTIONS : "DELETE_QUESTIONS"
}